100-hours-a-week/10-team-joytas-dao-fe

- src/components/lounge/LoungeContainer.tsx
> [버그] 빌드 실패 수정

- src/App.tsx
- 이 PR은 화면 구분선 색 수정을 위한 PR 입니다.
- ✨ 화면 테두리 색 변경
> [스타일] 화면 구분선 색 수정

- src/assets/models/MyRoomModel4.tsx
- 이 PR은 모델 주소 변경을 위한 PR입니다.
- ✨ 모델 gltf 로드 주소 변경
> [버그] 모델 주소 변경

- src/App.tsx
- src/pages/lounge/LoungeObjets.tsx
- src/pages/user/UserInvite.tsx
- src/pages/user/UserInviteStyle.tsx
- src/static.ts
- 이 PR은 라운지 초대 및 라운지 상세 페이지 추가을 위한 PR입니다.
- ✨ 라운지 유저 초대 페이지 추가
- ✨ 라운지 상세 페이지 수정
|라운지 초대|라운지 상세|
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/17fc8757-71f1-472a-a8f3-db0906d109bc)|![image](https://github.com/user-attachments/assets/ad4a1837-181e-49b2-981e-3379ed3c9bcb)|
> [기능] 라운지 초대 추가 및 라운지 상세 페이지 수정

- src/components/Header.tsx
- src/components/LayoutStyle.tsx
- src/components/Menu.tsx
- src/components/MenuStyle.tsx
- src/pages/login/Login.tsx
- src/pages/login/LoginStyles.tsx
- 이 PR은 메뉴 추가를 위한 PR입니다.
- ✨ 메뉴 추가
|메뉴|
|:---:|
|![image](https://github.com/user-attachments/assets/90e1b028-1ff3-43b1-8843-ebcf6fb27ed1)|
> [기능] 메뉴 추가

- package-lock.json
- package.json
- src/components/call/Video.tsx
- src/components/call/VideoContainer.tsx
- src/components/call/VideoStyle.tsx
- src/pages/objet/ObjetCall.tsx
- src/pages/objet/ObjetCallStyle.tsx
- src/pages/objet/ObjetStyles.tsx
- 이 PR의 webRTC 통화 기능을 추가하기 위한 PR입니다.
- ✨ 소켓 의존성 추가
- ✨ rtc기능 추가
> [기능] webRTC 통화 기능 추가

- .eslintrc.cjs
- eslint 수정
- ✨ `@typescript-eslint/no-unused-vars` 에러 무시
> [버그] eslint 수정

- src/components/Modal.tsx
- src/components/objet/Chat.tsx
- src/pages/lounge/Lounge.tsx
- src/pages/lounge/LoungeObjets.tsx
- src/pages/myRoom/MyRoomObjets.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/UpdateObjet.tsx
- src/pages/objet/newObjet/NewObjet.tsx
- src/pages/user/UserList.tsx
- 빌드 에러 해결
- ✨ unused 변수 및 컴포넌트 수정
> [버그] 빌드 unused 에러 해결

- src/App.tsx
- src/components/Header.tsx
- src/components/notification/NotificationItem.tsx
- src/global/globalStyles.tsx
- src/pages/notification/Notification.tsx
- src/pages/notification/NotificationStyles.tsx
- src/pages/user/UserList.tsx
- src/pages/user/UserListStyle.tsx
- src/static.ts
- src/utils/formatDatetime.tsx
- 알림 목록
- ✨ 알림 목록 페이지 추가
- ✨ 빈 화면 글로벌 컴포넌트 추가
|알림 목록 페이지| 빈 화면|
|---|---|
|![](https://github.com/user-attachments/assets/491d0187-e028-4c64-b5d8-87c418908353)| ![](https://github.com/user-attachments/assets/0740e545-aca9-4053-be96-dadfe58170d0)|
> [기능] 알림 목록 페이지 추가

- src/static.ts
- 이 PR은 API 엔드포인트 추가를 위한 PR입니다.
- ✨ API 엔드포인트 추가
> [기능] API 엔드포인트 추가

- src/assets/models/MyRoomModel4.tsx
- src/assets/models/MyRoomModel5.tsx
- 마이룸 모델 경량화
- ✨ 마이룸 모델4 매쉬 삭제
- ✨ 마이룸 모델5 매쉬 삭제
> [기능] 마이룸 모델 경량화

- src/components/Menu.tsx
- src/components/call/Video.tsx
- src/pages/objet/ObjetCall.tsx
- src/pages/user/UserDelete.tsx
> [버그] 스타일 모듈 설치경로 수정

- src/pages/lounge/LoungeStyles.tsx
- 이 PR은 라운지 생성 페이지 스타일 수정을 위한 PR입니다.
- ✨ 라운지 생성 페이지 스타일 수정
> [스타일] 라운지 생성 페이지 스타일 수정

- src/App.tsx
- src/components/user/UserListItem.tsx
- src/global/myRoomModels.tsx
- src/pages/myRoom/CreateMyRoom.tsx
- src/pages/myRoom/MyRoom.tsx
- src/pages/myRoom/MyRoomStyles.tsx
- src/pages/objet/ObjetStyles.tsx
- src/pages/user/UserDetail.tsx
- src/static.ts
- 마이룸 api 연결
- ✨ 마이룸 생성
- ✨ 마이룸 상세 조회
- ✨ 마이룸 수정
- ✨ 다른 유저의 마이룸 조회
> [기능] 마이룸 API 연결

- src/components/objet/NoPrevObjet.tsx
- src/components/objet/NoPrevObjetStyle.tsx
- src/components/objet/ObjetComponentStyles.tsx
- src/components/objet/ObjetPreview.tsx
- src/pages/home/Home.tsx
- src/pages/home/HomeStyles.tsx
- src/static.ts
- 이 PR은 메인 페이지 오브제 프리뷰 API 연결을 위한 PR입니다.
- ✨ 오브제 프리뷰 수정
- ✨ 오브제 프리뷰 API 연결
- ✨ 오브제 프리뷰 데이터 없을 시 안내 컴포넌트 추가
|오브제 프리뷰|
|:---:|
|![image](https://github.com/user-attachments/assets/77f01a2a-0c68-45fe-84bf-459889446635)|
> [기능] 메인 페이지 오브제 프리뷰 API 연결

- src/components/Menu.tsx
- src/components/MenuStyles.tsx
- src/static.ts
- 이 PR은 로그아웃 API 연결을 위한 PR입니다.
- ✨ 로그아웃 API 연결
> [기능] 로그아웃 API 연결

- src/components/objet/NoPrevObjetStyle.tsx
- src/pages/login/LoginStyles.tsx
- 이 PR은 프리뷰 및 로그인 버튼 스타일 수정을 위한 PR입니다.
- ✨ 메인 페이지 오브제 생성 버튼 스타일 수정
- ✨ 로그인 버튼 스타일 수정
> [스타일] 프리뷰 및 로그인 버튼 스타일 수정

- src/components/Footer.tsx
- src/components/Menu.tsx
- src/components/user/NicknameInputField.tsx
- src/components/user/ProfileImageUploader.tsx
- src/pages/home/Home.tsx
- src/pages/myRoom/MyRoom.tsx
- src/pages/user/FirstProfile.tsx
- src/pages/user/ModifyProfile.tsx
- src/pages/user/ProfileStyles.tsx
- src/static.ts
- src/types/ProfileType.ts
- src/utils/validation.ts
- 이 PR은 유저 프로필 조회/수정 API 연결을 위한 PR입니다.
- ✨ 유저 초기 프로필 설정 페이지 API 연결
- ✨ 유저 프로필 수정 페이지 API 연결
- ✨ 유저 프로필 연동
> [기능] 유저 프로필 조회/수정 API 연결

- src/components/user/UserListItem.tsx
- src/pages/user/UserDetail.tsx
- src/pages/user/UserList.tsx
- 빌드 수정
- ✨ 유저 목록, 유저 상세 코드 수정
> [빌드] 유저 관련 빌드 수정

- src/App.tsx
- src/components/objet/InputItem.tsx
- src/global/objetModels.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/ObjetStyles.tsx
- src/pages/objet/UpdateObjet.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- src/pages/objet/newObjet/NewObjet.tsx
- src/pages/objet/newObjet/SelectObjetType.tsx
- src/static.ts
- 오브제 생성 API 연결
- ✨ 오브제 생성 API 연결
- ✨ 오브제 관련 경로 수정
- ✨ 오브제 관련 빌드 수정
> [기능] 오브제 생성 api 연결 및 경로 수정

- src/App.tsx
- src/assets/mock/userData.tsx
- src/components/Modal.tsx
- src/components/ModalStyles.tsx
- src/pages/objet/ObjetCall.tsx
- src/pages/objet/ObjetChatting.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/ObjetStyles.tsx
- src/pages/objet/UpdateObjet.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- src/pages/user/UserList.tsx
- 오브제 조회/수정/ 삭제 API 연결
- ✨ 오브제 조회 api 연결
- ✨ 오브제 수정 api 연결
- ✨ 오브제 삭제 api 연결
- ✨ 오브제 생성자만 수정/삭제 권한 제공
- ✨ 유저 목업 데이터 생성
- ❗️ 유저 목록, 오브제 뷰어 목록, 채팅 미리보기 연결 추가 필요
- ❗️오브제 생성 버튼 클릭 시 유효성 검사 추가
- ❗️오브제 삭제 후 페이지 이동할 라운지 ID 설정
> [기능] 오브제 API 연결 및 유저 목업데이터 추가

- src/App.tsx
- src/components/Modal.tsx
- src/components/ModalStyles.tsx
- src/pages/user/ModifyProfile.tsx
- src/pages/user/UserDelete.tsx
- src/pages/user/UserDeleteStyles.tsx
- 이 PR은 회원 탈퇴 API 연결을 위한 PR입니다.
- ✨ 회원탈퇴 모달 추가
- ✨ 회원탈퇴 API 연결
|회원탈퇴|회원탈퇴 모달|
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/fcc7a67c-c5a8-4deb-a734-94eb20b3f2f5)|![image](https://github.com/user-attachments/assets/cdd53094-bdc8-47ac-86ae-0c9d1b3ecb97)|
> [기능] 회원 탈퇴 API 연결

- src/pages/myRoom/MyRoom.tsx
- 마이룸 미존재시 마이룸 생성 페이지로 리다이렉트 기능 추가 
- ✨ 마이룸 미존재하는 경우, 마이룸 페이지 접속 시도 시 마이룸 생성 페이지로 리다이렉트
> [버그] 마이룸 생성페이지 리다이렉트 추가

- src/components/LayoutStyles.tsx
- src/pages/myRoom/CreateMyRoom.tsx
- src/pages/myRoom/MyRoomStyles.tsx
- src/pages/objet/ObjetStyles.tsx
- 이 PR은 스타일 수정을 위한 PR입니다.
- ✨ 푸터 이미지 모양 변경
- ✨ 마이룸 생성 padding 변경
- ✨ 오브제 모양 선택 버튼 위치 변경
> [스타일] 스타일 수정

- src/components/lounge/LoungeContainer.tsx
- src/pages/lounge/Lounge.tsx
- src/pages/lounge/NewLounge.tsx
- src/pages/myRoom/CreateMyRoom.tsx
- src/pages/myRoom/MyRoom.tsx
- src/pages/objet/UpdateObjet.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- 사소한 버그들을 수정했습니다.
- ✨ 페이지 리다이렉트 경로 수정
- ✨ 라운지 생성 시 라운지 관리자값 수정
- ✨ 마이룸 생성 시 마이룸으로 이동
- ✨ 중복 URL 오류로 인한 이미지 업로드 로직 변경 (`static의 URL`과 `내장 URL` 충돌 이슈)
> [버그] 페이지 경로 및 리다이렉트 수정

- src/App.tsx
- src/pages/lounge/Lounge.tsx
- src/pages/lounge/LoungeObjets.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/UpdateObjet.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- 이 PR은 useLocation 대신 useParams로 변경을 위한 PR입니다.
- ✨ useLocation 대신 useParams로 변경
> [수정] useLocation 대신 useParams로 변경

- src/components/call/Video.tsx
- src/components/call/VideoContainer.tsx
- 시그널링 서버 인증 요청 구현
- 시그널링 서버 인증 & 유저 데이터를 연결
- ✨ 음성 채팅 시그널링 서버에 토큰과 objet_id 전송
- ♻️  시그널링 서버에 보내는 데이터 변경 email -> nickname & room -> objet
- ✨ 유저 토큰 및 닉네임 로컬 스토리지 데이터와 연결
> Feature/signaling auth : 시그널링 서버 인증 요청 구현

- src/assets/mock/userData.tsx
- src/components/Modal.tsx
- src/components/ModalStyles.tsx
- src/components/objet/InputItem.tsx
- src/pages/lounge/Lounge.tsx
- src/pages/lounge/LoungeObjets.tsx
- src/pages/myRoom/MyRoomObjets.tsx
- src/pages/objet/ObjetStyles.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- src/pages/objet/newObjet/SelectObjetType.tsx
- 마이룸 - 라운지별 오브제 API 연결
- ✨ 라운지별 오브제 조회
- ✨ 라운지 목록 모달 스타일 수정
- 목록에 `전체` 추가
- 선택되었던 라운지 표시
| 라운지 목록 모달 | 라운지 목록 모달 (특정 라운지 선택한 상태) |
|---|---|
|![](https://github.com/user-attachments/assets/e25fc1ee-7899-46a2-ab8f-ed60ae93bc6b) | ![](https://github.com/user-attachments/assets/ed5c4e0f-7ef4-490d-af60-589e1cc473c3)|
> [기능] 마이룸 라운지별 오브제 api 연결

- src/components/Modal.tsx
- src/components/lounge/LoungeDrop.tsx
- src/components/lounge/LoungeDropStyle.tsx
- src/pages/lounge/Lounge.tsx
- src/pages/lounge/LoungeStyles.tsx
- 이 PR은 라운지 삭제 API 연결을 위한 PR입니다.
- ✨ 라운지 삭제 모달 추가
- ✨ 라운지 삭제 API 연결
> [기능] 라운지 삭제 API 연결

- src/pages/lounge/LoungeObjets.tsx
- 이 PR은 오브제 클릭 시 오브제 상세 페이지로 이동을 위한 PR입니다.
- ✨ 라운지 상세 페이지에서 오브제 클릭 시 오브제 상세 페이지로 이동
https://github.com/user-attachments/assets/d1c30fcd-1fdf-47d0-82a9-4a507aad3e73
> [기능] 오브제 클릭 시 오브제 상세 페이지로 이동

- package-lock.json
- package.json
- src/components/Footer.tsx
- src/components/Menu.tsx
- src/components/call/VideoContainer.tsx
- src/components/objet/ObjetPreview.tsx
- src/pages/home/Home.tsx
- src/pages/lounge/Lounge.tsx
- src/pages/lounge/NewLounge.tsx
- src/pages/myRoom/MyRoom.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/user/FirstProfile.tsx
- src/pages/user/ModifyProfile.tsx
- src/pages/user/UserDelete.tsx
- src/pages/user/UserDetail.tsx
- src/store/userStore.ts
- 이 PR은 상태관리 라이브러리 추가를 위한  PR입니다.
- ✨ zustand 추가
- ✨ zustand 사용하여 유저 정보 관리
> [기능] 상태관리 라이브러리 추가

- src/App.tsx
- src/components/dropdown/Dropdown.tsx
- src/components/user/UserListItem.tsx
- src/pages/user/UserList.tsx
- src/static.ts
- 이 PR은 라운지 유저 초대 API 연결을 위한 PR입니다.
- ✨ 라운지 유저 초대  API 연결
- ✨ 유저 목업 데이터 수정
> [기능] 라운지 유저 초대 API 연결

- src/components/objet/ObjetComponentStyles.tsx
- src/components/objet/ObjetPreview.tsx
- src/pages/lounge/LoungeObjets.tsx
- 이 PR은 오브제 링크 수정을 위한 PR입니다.
- ✨ 라운지 상세 페이지에서 오브제 상세 세페이지 이동 링크 수정
- ✨ 메인 페이지에서 오브제 상세 페이지로 이동
> [수정] 오브제 링크 수정

- .gitignore
- package-lock.json
- package.json
- src/main.tsx
- vite.config.ts
- 이 PR은 sentry 추가를 위한 PR입니다.
- ✨ 센트리 추가
> [기능] sentry 추가

- src/App.tsx
- 라우터 기본 경로 설정
- ✨ '/' 경로로 접근 시 메인 페이지로 이동하도록 설정
- ✨ home -> login 이름 변경
> [기능] 라우터 기본 경로 설정

- src/components/Layout.tsx
- src/hooks/useInfo.ts
- src/pages/home/Home.tsx
- src/pages/home/HomeStyles.tsx
- src/store/userStore.ts
- 이 PR은 유저 정보 관리 수정을 위한 PR입니다.
- ✨ 유저 정보 훅 추가
- ✨ 홈 화면 변경
> [기능] 유저 정보 관리 수정

- src/App.tsx
- src/components/Menu.tsx
- src/hooks/useInfo.ts
- src/pages/user/UserDelete.tsx
- src/static.ts
- 이 PR은 네비게이션 주소 변경을 위한 PR입니다.
- ✨ 네비게이션 주소 변경
> [수정] 네비게이션 주소 변경

- src/pages/login/Login.tsx
- src/pages/login/LoginStyles.tsx
- 이 PR은 로그인 페이지 이미지 lazy 로딩을 위한 PR입니다.
- ✨ 이미지 lazy 로딩 추가
- ✨ 위치 조정
> [기능] 로그인 페이지 이미지 lazy 로딩

- index.html
- 이 PR은 index.html hotjar 설정 제거
- ✨ 핫자 index.html 설정 제거
> [수정] index.html hotjar 설정 제거

- src/components/call/VideoContainer.tsx
- src/main.tsx
- src/static.ts
- 이 PR은 주소 env로 변경을 위한 PR입니다.
- ✨ 민감 주소 env로 변경
> [기능] 주소 env로 변경

- src/pages/lounge/LoungeObjets.tsx
- 이 PR은 라운지 상세 페이지에 오브제 이름 추가를 위한 PR입니다.
- ✨ 오브제 이름 추가
|라운지 상세|
|:---:|
|![image](https://github.com/user-attachments/assets/d9c5bcfc-b349-4fd2-9ec1-252e5d1ec2c1)|
> [기능] 라운지 상세 페이지에 오브제 이름 추가

- src/components/call/VideoContainer.tsx
- 이 PR은 webRTC 서버 url 수정을 위한 PR입니다.
- ✨ WebRTC 주소 변경
> [수정] webRTC 서버 url 수정

- src/components/dropdown/Dropdown.tsx
- src/components/lounge/LoungeContainer.tsx
- src/hooks/useInfo.ts
- src/pages/lounge/NewLounge.tsx
- src/pages/myRoom/MyRoom.tsx
- src/pages/objet/ObjetCall.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/UpdateObjet.tsx
- src/pages/user/FirstProfile.tsx
- src/pages/user/ModifyProfile.tsx
- src/pages/user/UserDetail.tsx
- src/store/userStore.ts
- 이 PR은 쿠키 설정 포함을 위한 PR입니다.
- ✨ 쿠키 설정 포함
> feat: 쿠키 설정 포함

- src/components/lotties/LoadingLottie.tsx
- src/components/lotties/NoDataLottie.tsx
- 이 PR은 센트리 로띠 경고 수정을 위한 PR입니다.
- ✨ 로띠 의존성 라이브러리 수정
> [수정] 센트리 로띠 경고 수정

- package-lock.json
- package.json
- src/components/objet/Chat.tsx
- src/components/objet/ChatStyles.tsx
- src/components/objet/GoCommunityBtn.tsx
- src/pages/objet/ObjetCall.tsx
- src/pages/objet/ObjetChatting.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/ObjetStyles.tsx
- src/pages/objet/UpdateObjet.tsx
- src/static.ts
- src/store/objetStore.ts
- src/utils/stomp.ts
- 채팅 기능 연결
- ✨ 채팅 서버 연결 (stomp 설정)
- ✨ `오브제 상세조회 > 버튼` 텍스트 수정
- ✨ 스타일 컴포넌트 `isActive` 경고 해결
> [기능] 채팅 서버 연결

- package-lock.json
- package.json
- src/components/Header.tsx
- src/components/LayoutStyles.tsx
- src/components/Menu.tsx
- src/components/MenuStyles.tsx
- 이 PR은 햄버거 메뉴버튼 수정을 위한 PR입니다.
- ✨ 햄버거 버튼 수정
https://github.com/user-attachments/assets/ce9c149b-ce80-4c04-9d62-4235eb6d7f2a
> [스타일] 햄버거 메뉴버튼 수정

- src/components/modal/Modal.tsx
- src/pages/objet/ObjetChatting.tsx
- 세부 버그 수정
- ✨ 채팅 sender id 수정
- ✨ 오브제 삭제 함수화
> [수정] 채팅, 오브제 삭제 버그 해결

- src/pages/lounge/NewLounge.tsx
- src/pages/myRoom/CreateMyRoom.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- 이 PR은 오브제 관련 버그 수정을 위한 PR입니다.
- ✨ 오브제 조회 404 처리
- ✨ 오브제 생성 4XX 처리
> [수정] 오브제 관련 버그 수정

- src/pages/lounge/LoungeStyles.tsx
- src/pages/lounge/NewLounge.tsx
- 이 PR은 라운지 인풋 포커스 설정을 위한 PR입니다.
- ✨ 라운지 이름 자동 focus
- ✨ 라운지 관리자 focus 불가
> [기능] 라운지 인풋 포커스 설정

- src/index.css
- src/pages/myRoom/MyRoom.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/ObjetStyles.tsx
- src/pages/user/FirstProfile.tsx
- src/pages/user/ProfileStyles.tsx
- 세부 버그 수정
- ✨ 첫 프로필 설정 버튼 디자인 변경
- ✨ 마이룸 모델 조회 오류 수정
- ✨ 음성통화 풀방 토스트 수정
| 기존 화면 | 마우스 호버|
|---|---|
|![](https://github.com/user-attachments/assets/57f0c850-ecfd-4884-9828-0a981f61aa28)| ![](https://github.com/user-attachments/assets/003f5a64-d7d7-4f24-b585-ac6844f59aa8)|
> [수정] 세부 버그 수정

- src/components/user/UserListItem.tsx
- src/pages/lounge/LoungeObjets.tsx
- src/pages/lounge/ObjetModels.tsx
- src/pages/user/UserList.tsx
- src/static.ts
- src/types/ModelType.ts
- 이 PR은 검색 API 연결 및 라운지 상세 페이지 수정을 위한 PR입니다.
- ✨ 검색 API 연결
- ✨ 라운지 상세 페이지 수정
> [기능] 검색 API 연결

- src/components/user/UserListItem.tsx
- src/pages/user/UserDetail.tsx
- 이 PR은 유저 프로필 타입으로 인한 빌드 실패 수정을 위한 PR입니다.
- ✨ type 수정
> [수정] 유저 프로필 타입으로 인한 빌드 실패 수정

- src/pages/lounge/LoungeObjets.tsx
- src/pages/lounge/ObjetModels.tsx
- src/pages/objet/ObjetDetail.tsx
- src/types/ModelType.ts
- 이 PR은 오브제 관련 수정을 위한 PR입니다.
- ✨ url상 오브제 아이디가 바뀌어도 상세 페이지가 바뀌지 않는 버그 수정
- ✨ 라운지에서 오브제 클릭 시 오브제 이동 경로 수정
> [수정] 오브제 관련 수정

- src/pages/user/UserDetail.tsx
- src/pages/user/UserList.tsx
- src/static.ts
- 마이룸 및 유저 목록 관련 코드 수정
- ✨ 다른 유저 마이룸 상세 조회 오류 해결
- ✨ 유저 검색 입력창 자동 포커스 기능 추가
- closing #92
> [수정] 다른 유저 마이룸 상세조회 오류 해결

- package-lock.json
- package.json
- src/App.tsx
- src/components/Menu.tsx
- src/components/dropdown/Dropdown.tsx
- src/components/modal/Modal.tsx
- src/components/user/UserListItem.tsx
- src/pages/lounge/NewLounge.tsx
- src/pages/myRoom/CreateMyRoom.tsx
- src/pages/myRoom/MyRoom.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/UpdateObjet.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- src/pages/user/ModifyProfile.tsx
- src/pages/user/UserDelete.tsx
- src/pages/user/UserListStyles.tsx
- 이 PR은 토스트 메세지 추가를 위한 PR입니다.
- ✨ 토스트 메세지 추가
- ✨ 사이브바에서 프로필 이미지 스타일 변경
> [기능] 토스트 메세지 추가

- src/hooks/useNotification.ts
- src/pages/notification/Notification.tsx
- src/store/notiStore.ts
- 이 PR은 채팅 버그 수정을 위한 PR입니다.
- ✨ 채팅 버그 수정
> [수정] 채팅 버그 수정

- src/components/Layout.tsx
- src/hooks/useNotification.ts
- 이 PR은 알림 토스트 메세지 추가를 위한 PR입니다.
- ✨ 알림 토스트 메세지 추가
> [기능] 알림 토스트 메세지 추가

- src/components/Layout.tsx
- src/components/call/VideoContainer.tsx
- src/hooks/useNotification.ts
- src/pages/lounge/NewLounge.tsx
- src/pages/objet/ObjetCall.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/UpdateObjet.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- src/pages/user/ModifyProfile.tsx
- src/pages/user/UserDelete.tsx
- src/utils/stomp.ts
- 이 PR은 디버깅용 콘솔 삭제를 위한 PR입니다.
- ✨ 콘솔 삭제
> [리팩토링] 디버깅용 콘솔 삭제

- src/pages/home/Home.tsx
- 이 PR은 캐러셀 좌우 화살표 추가를 위한 PR입니다.
- ✨ 캐러셀 좌우 화살표 추가
> [기능] 캐러셀 좌우 화살표 추가

- src/components/call/VideoContainer.tsx
- src/pages/objet/ObjetCall.tsx
- 음성통화 참가 요청 데이터 변경
- 🐛 음성통화 참가 요청 데이터 변경 objetId -> loungeId
- closes #111
> fix: 음성통화 참가 요청 데이터 변경

- src/pages/user/FirstProfile.tsx
- src/pages/user/ModifyProfile.tsx
- src/pages/user/ProfileStyles.tsx
- src/static.ts
- 이 PR은 프로필 변경 및 초기 설정 로직 수정을 위한 PR입니다.
- ✨ 초기 프로필 설정 및 프로필 변경 로직 수정
- ✨ 프로필 변경 api endpoint 수정
> [수정] 프로필 변경 및 초기 설정 로직 수정

- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/ObjetStyles.tsx
- src/pages/objet/newObjet/SelectObjetType.tsx
- 이 PR은 채팅 없을 시 버튼 미노출 수정을 위한 PR입니다.
- ✨ 채팅 없을 시, 채팅 입장 버튼 및 음성통화 참가 버튼 노출되도록 수정
> [수정] 채팅 없을 시 버튼 미노출 수정

- src/components/call/VideoContainer.tsx
- src/components/call/VideoStyles.tsx
- src/pages/notification/Notification.tsx
- src/pages/objet/ObjetCall.tsx
- src/pages/objet/ObjetCallStyles.tsx
- src/pages/objet/ObjetStyles.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- src/pages/objet/newObjet/SelectObjetType.tsx
- 이 PR은 오브제 멤버 검색 기능 추가 및 오브제 통화 관련 수정, 알림 수정을 위한 PR입니다.
- ✨ 오브제 멤버 검색 로직 추가
- ✨ 오브제 생성 페이지 스타일 수정
- ✨ 오브제 멤버 검색 시 발생하는 에러 임시방편으로 수정
- ✨ 오브제 통화 시 본인 이름 노출
- ✨ 알림 날짜 최신 순 정렬
> [기능] 오브제 멤버 검색 기능 추가

- src/pages/objet/UpdateObjet.tsx
- src/pages/user/UserList.tsx
- 이 PR은 유저 검색 수정을 위한  PR입니다.
- ✨ 라운지 초대 유저 검색 api 변경
- ✨ 오브제 수정 시 에러 임시 수정
> [수정] 유저 검색 수정

- src/pages/home/Home.tsx
- src/pages/lounge/Lounge.tsx
- src/pages/objet/ObjetDetail.tsx
- 이 PR은 라운제, 오브제 삭제 시 토스트 메세지 노출을 위한 PR입니다.
- ✨ 삭제된 오브제 조회 시 토스트 메세지 노출
- ✨ 삭제된 라운지 조회 시 토스트 메세지 노출
- ✨ 로그아웃 후 재로그인 시 오브제 프리뷰 미노출 이슈 해결
> [수정] 버그 수정

- src/pages/lounge/Lounge.tsx
- 이 PR은 존재하지 않은 라운지 조회시 navigate되는 주소 변경
- ✨ navigate 주소 변경
> [수정] 라운지 navigate 주소 변경

- index.html
- src/assets/models/LoungeModel1.tsx
- src/assets/models/LoungeModel2.tsx
- src/assets/models/LoungeModel3.tsx
- src/assets/models/LoungeModel4.tsx
- src/components/Footer.tsx
- src/components/lounge/LoungeContainer.tsx
- src/index.css
- src/pages/login/LoginStyles.tsx
- src/pages/lounge/LoungeList.tsx
- src/pages/lounge/NewLounge.tsx
- src/pages/user/ProfileStyles.tsx
- 이 PR은 lazy loading 추가 및 최적화을 위한 PR입니다.
- ✨ 모델 컴포넌트 lazy loading 추가
- ✨ 이미지 lazy loading 추가
- ✨ 폰트 최적화 추가
> [수정] lazy loading 추가 및 최적화

- src/components/user/UserListItem.tsx
- src/pages/user/UserList.tsx
- 이 PR은 유저목록에서 자기 자신 제외를 위한 PR입니다.
- ✨ 유저 검색 결과에서 자신 제외 후 노출
> [수정] 유저목록에서 자기 자신 제외

- src/assets/models/MyRoomModel1.tsx
- src/assets/models/MyRoomModel2.tsx
- src/assets/models/MyRoomModel3.tsx
- src/assets/models/MyRoomModel4.tsx
- src/assets/models/MyRoomModel5.tsx
- src/assets/models/ObjetModel1.tsx
- src/assets/models/ObjetModel2.tsx
- src/assets/models/ObjetModel3.tsx
- src/components/lounge/LoungeContainer.tsx
- src/global/myRoomModels.tsx
- src/global/objetModels.tsx
- src/pages/lounge/LoungeList.tsx
- src/pages/lounge/NewLounge.tsx
- src/pages/lounge/ObjetModels.tsx
- src/pages/myRoom/MyRoom.tsx
- src/pages/objet/newObjet/SelectObjetType.tsx
- 이 PR은 lazy loading을 좀
- ✨ 오브제 모델 lazy loading 추가
- ✨ 마이룸 모델 lazy loading 추가
> [수정] 모델 lazy loading 추가

- src/pages/myRoom/MyRoom.tsx
- src/pages/objet/ObjetStyles.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- src/pages/user/UserDetail.tsx
- 마이룸, 오브제 생성 관련 버그 해결
- ✨ 다른 유저 마이룸 모델 번호 오류 해결
- ✨ 마이룸 이름, 오브제 이름, 오브제 상세 최대 입력 길이 설정
- ✨ 오브제 생성 버튼 위치 수정
- ✨ 마이룸 이름 수정 시도 후 취소 버튼 클릭 시 마이룸 이름 초기화
- closing #102 
- closing #116 
|버튼 위치 수정 전| 수정 후|
|---|---|
|![image](https://github.com/user-attachments/assets/13ac9a03-f718-469d-9843-8de7a50f8d4d)|![image](https://github.com/user-attachments/assets/2e11a5fa-ccad-46a5-823b-6529b868e677)|
> [수정] 마이룸, 오브제 관련 버그 해결

- src/App.css
- src/App.tsx
- src/components/Header.tsx
- src/components/LayoutStyles.tsx
- src/components/MenuStyles.tsx
- src/components/dropdown/DropdownStyles.tsx
- src/components/lotties/NoDataLottie.tsx
- src/components/objet/ChatStyles.tsx
- src/components/objet/ObjetComponentStyles.tsx
- src/global/globalStyles.tsx
- src/pages/home/HomeStyles.tsx
- src/pages/login/LoginStyles.tsx
- src/pages/lounge/LoungeStyles.tsx
- src/pages/myRoom/MyRoom.tsx
- src/pages/myRoom/MyRoomStyles.tsx
- src/pages/notification/Notification.tsx
- src/pages/notification/NotificationStyles.tsx
- src/pages/objet/ObjetStyles.tsx
- src/pages/user/UserDeleteStyles.tsx
- 이 PR은 레이아웃 스타일 변경을 위한 PR입니다.
- ✨ 레이아웃 스타일 변경
|600px 이상|600px 미만|
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/5d0f70df-695a-45a1-95cb-53f82d961413)|![image](https://github.com/user-attachments/assets/eb060375-bd1f-48ef-bd04-2723e0c49292)|
> [수정] 레이아웃 스타일 변경

- src/components/call/VideoContainer.tsx
- src/components/call/VideoStyles.tsx
- src/components/lounge/LoungeContainer.tsx
- src/pages/objet/ObjetCallStyles.tsx
- src/pages/objet/ObjetStyles.tsx
- 이 PR은 오브제 통화 레이아웃 변경을 위한 PR입니다
- ✨ 오브제 통화 크기 변경
|오브제 통화|
|:---:|
|![image](https://github.com/user-attachments/assets/f544c018-7ce7-4173-84d6-a9ce00e28b49)|
> [수정] 오브제 통화 레이아웃 변경

- index.html
- 이 PR은 구글 태그 매니저 추가을 위한 PR입니다.
- ✨ 태그 매니저 추가
> [기능] 구글 태그 매니저 추가

- src/pages/objet/UpdateObjet.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- src/pages/user/FirstProfile.tsx
- src/pages/user/ModifyProfile.tsx
- src/static.ts
- 오브제 API 및 수정 로직 수정 PR
- ✨ 이미지 업로드 API 경로 수정
- ✨ 오브제 생성 및 수정 API 수정
- ✨ 오브제 수정 시 변경 내역있는지 확인 기능 추가
- closes #139
> [기능 및 수정] 오브제 API 및 수정 로직 수정

- index.html
- 이 PR은 구글 애널리틱스 추가
- ✨ 구글 애널리틱스
> [기능] 구글 애널리틱스 추가

- package-lock.json
- package.json
- src/firebase.ts
- 이 PR은 firebase 연결을 위한 PR입니다.
- ✨ firebase 연결
> [기능] firebase 연결

- index.html
- 이 PR은 구글 에널리틱스 변경을 위한 PR입니다.
- ✨ 구글 에널리틱스 주소 변경
> [수정] 구글 에널리틱스 변경

- src/components/Footer.tsx
- src/components/lounge/LoungeContainer.tsx
- 이 PR은 커스텀 이벤트 추가를 위한 PR입니다.
- ✨ 푸터 이벤트 추가
- ✨ 라운지 이벤트 추가
> [기능] 커스텀 이벤트 추가

- src/static.ts
- 이 PR은 stomp url 변경을 위한 PR입니다.
- ✨ stomp 주소 env로 변경
> [수정] stomp url 변경

- src/App.tsx
- src/components/dropdown/Dropdown.tsx
- src/components/objet/ObjetPreview.tsx
- src/pages/lounge/LoungeObjets.tsx
- src/pages/objet/ObjetCall.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/UpdateObjet.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- src/static.ts
> feat: 라우터 경로 수정

- src/pages/myRoom/CreateMyRoom.tsx
- src/pages/objet/UpdateObjet.tsx
- 마이룸 버그 수정
- ✨ 마이룸 생성 실패 토스트 수정
- ✨ 마이룸 수정 로직 수정
> [수정] 마이룸 버그 수정

- src/assets/models/ObjetModel1.tsx
- src/components/lounge/LoungeContainer.tsx
- src/pages/lounge/ObjetModels.tsx
- 이 PR은 io 도메인 라운지 페이지 내 버그 수정을 위한 PR입니다.
- ✨ 버그 수정
- ✨ 오브제 관련 수정
> [수정] io 도메인 라운지 페이지 내 버그 수정

- src/static.ts
- 이 PR은 채팅 연결 안됨 버그 수정을 위한 PR입니다.
- ✨ url 설정 변경
> [수정] 채팅 연결 안됨 버그 수정

- src/assets/models/MyRoomModel4.tsx
- src/global/myRoomModels.tsx
- src/pages/myRoom/MyRoom.tsx
- 마이룸 모델 각도 수정
- ✨마이룸 각도 조정
|모델1|모델2|모델3|모델4|모델5|
|---|---|---|---|---|
|![image](https://github.com/user-attachments/assets/28765c42-d59f-4fc5-9101-a659fd16011d)|![image](https://github.com/user-attachments/assets/39bc35ad-b198-4b06-92bd-38d8fb09180a)|![image](https://github.com/user-attachments/assets/248d2ea2-a7ba-433c-9f71-c76a299691ce)|![image](https://github.com/user-attachments/assets/bd1ec7a3-4745-4f33-a913-c3f12218b72c)|![image](https://github.com/user-attachments/assets/0daf176e-05d5-40a2-9288-2c81f1c9e441)|
> [수정] 마이룸 모델 각도 수정

- src/components/call/Video.tsx
- src/components/call/VideoContainer.tsx
- src/components/call/VideoStyles.tsx
- src/pages/objet/ObjetCallStyles.tsx
- 이 PR은 영상을 음성으로 변경하기 위한 PR입니다.
- ✨ 영상통화 -> 음성통화로 변경
> [기능] 음성통화로 변경

- src/App.tsx
- src/components/objet/ObjetPreview.tsx
- src/components/user/UserListItem.tsx
- src/pages/lounge/Lounge.tsx
- src/pages/lounge/LoungeObjets.tsx
- src/pages/objet/ObjetCall.tsx
- src/pages/objet/ObjetDetail.tsx
- src/pages/objet/UpdateObjet.tsx
- src/pages/objet/newObjet/InputObjetInfo.tsx
- src/static.ts
- src/types/ModelType.ts
> [수정] 라우터 수정

- src/components/dropdown/Dropdown.tsx
- src/pages/lounge/LoungeObjets.tsx
- src/pages/lounge/LoungeStyles.tsx
- src/pages/myRoom/MyRoomObjets.tsx
- 라운지별 오브제 미조회 오류 해결
- ✨ 데이터 처리 및 로딩 처리 추가
> [수정] 라운지별 오브제 오류 해결

- src/components/Footer.tsx
- 푸터 수정
- ✨ 오브제 페이지에서 푸터 강조 표시
> [수정] 오브제 관련 푸터 수정
